---
development:
  cloud_name: hzew3wraw
  api_key: '441451692895287'
  api_secret: kzPB71_yUaaweDaIRIL4zti8kzU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hzew3wraw
  api_key: '441451692895287'
  api_secret: kzPB71_yUaaweDaIRIL4zti8kzU
  enhance_image_tag: true
  static_image_support: true
  cdn_subdomain: true
test:
  cloud_name: hzew3wraw
  api_key: '441451692895287'
  api_secret: kzPB71_yUaaweDaIRIL4zti8kzU
  enhance_image_tag: true
  static_image_support: false
